version: '3'

services:
  zerotierbridge:
    container_name: zerotierbridge
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ARCH: amd64
        VERSION: 1.6.6
    restart: always
    privileged: true
    volumes:
      - zt_config:/var/lib/zerotier-one
    environment:
      - ZT_NETWORKS=NETWORK_ID_1 NETWORK_ID_2 NETWORK_ID_3
      - ZT_BRIDGE=true
volumes:
  zt_config: